SHELL:= /bin/bash

qa:
	$(MAKE) -C pin-reader qa
	$(MAKE) -C pin-writer qa

format:
	$(MAKE) -C pin-reader format
	$(MAKE) -C pin-writer format


clean:
	$(MAKE) -C pin-reader clean
	$(MAKE) -C pin-writer clean
