FROM python:3.12-slim-bullseye

RUN apt update && apt install -y curl libpq-dev gcc make

RUN curl -sSL https://install.python-poetry.org | \
POETRY_HOME=/opt/poetry POETRY_VERSION=1.5.1 python && \
cd /usr/local/bin && \
ln -s /opt/poetry/bin/poetry && \
poetry config virtualenvs.create false

COPY ./pyproject.toml ./poetry.lock* ./README* ./LICENSE* /app/
WORKDIR /app
RUN poetry install --no-root

ENTRYPOINT /app/dev_tools/entrypoint.sh
