FROM python:3.12-slim-bullseye

RUN apt update && apt install -y curl libpq-dev gcc make

RUN pip install poetry==1.5.1
RUN poetry config virtualenvs.create false

COPY ./pyproject.toml ./poetry.lock* ./README* ./LICENSE* ./dev_tools/ /app/
WORKDIR /app
RUN poetry install --no-root

COPY ./api /app/api

ENTRYPOINT /app/dev_tools/entrypoint.sh
